package com.activityplatform.backend.audit.domain;

public enum AuditAction {
  AUTH_LOGIN,
  AUTH_LOGOUT,
  ACTIVITY_CREATED,
  EVIDENCE_SUBMITTED,
  EVIDENCE_REVIEWED,
  STATUS_CHANGED,
  USER_CREATED,
  USER_STATUS_CHANGED,
  USER_UPDATED,
  WORKFLOW_CHANGED,
  REPORT_EXPORT_COMPLETED,
  REPORT_EXPORT_REQUESTED,
  REPORT_SUMMARY_VIEWED,
  NOTIFICATION_QUEUED,
  NOTIFICATION_STATUS_CHANGED,
  USER_ROLES_UPDATED
}
